language: python
python:
  - "3.10"
  - "3.11"
  - "3.12"
cache: pip
install:
  - pip install -r requirements.txt
  - pip install -U pytest
  - pip install -U pytest-mpl
  - pip install -U pytest-cov codecov
script:
  - pytest methcomp --mpl-generate-path=methcomp/tests/baseline -p no:warnings
  - pytest methcomp --mpl -p no:warnings
  - pytest --cov-report=xml --cov=methcomp methcomp/tests/
after_succes:
  - codecov
